version: '3.8'

services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80" # Access frontend at http://localhost:8080
    volumes:
      - ./frontend:/usr/share/nginx/html # Mount frontend files to Nginx's root directory
    networks:
      - webnet

  backend:
    image: php:7.4-apache # PHP and Apache image
    ports:
      - "8081:80" # Access backend at http://localhost:8081
    volumes:
      - ./backend:/var/www/html # Mount backend files to Apache's root directory
    networks:
      - webnet

networks:
  webnet:
